

Source :
  name : List of Committees
  urls: 
    -http://download.srv.cs.cmu.edu/~mmcgloho/fec/data/committees1.txt
    -http://download.srv.cs.cmu.edu/~mmcgloho/fec/data/committees2.txt

Source:
  name : list of fines
  url : ftp://ftp.fec.gov/FEC/ClosedAdminFines_Web.txt


